version: 0.2
phases:
  build:
    commands:
      - echo "Retrieve authentication token..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY_URI

      - echo "Build and push image..."
      - docker build -t $ECR_REGISTRY_URI/$ECR_IMAGE_NAME:latest .
      - docker push $ECR_REGISTRY_URI/$ECR_IMAGE_NAME:latest