version: 0.2
phases:
  build:
    commands:
      - echo "Retrieve authentication token..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY_URI

      - echo "Build and push image..."
      - docker build -t $ECR_REGISTRY_URI/$ECR_IMAGE_NAME:latest .
      - docker push $ECR_REGISTRY_URI/$ECR_IMAGE_NAME:latest

      - echo "Fetch latest task definion..."
      - aws ecs describe-task-definition --task-definition task-tracker-td --query "taskDefinition" --output json > task_def.json
      - jq '.containerDefinitions[0].image = "<TASK_DEF_IMAGE>"' task_def.json 
      - printf '{"ImageURI":"%s"}' "$ECR_REGISTRY_URI/$ECR_IMAGE_NAME:latest" > image_details.json

artifacts:
  files:
  - "task_def.json"
  - ".aws/appspec.yml"
  - "image_details.json"